# This is a basic workflow to help you get started with Actions

name: static-page

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, next ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# @TODO: use custom github actions for webassembly compiling
jobs:
  deploy-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1 # faster CI

    - name: Install NPM packages
      uses: docker://node:12.10.0-alpine
      with:
        args: /bin/sh -c "cd /github/workspace/web-frontend && yarn install"

    - name: Web assembly build
      uses: docker://ghcr.io/mrcne/swe-dev
      with:
        args: /bin/bash -c "source /emsdk/emsdk_env.sh && cd /github/workspace && make js-es6"

    - name: Copy web assembly
      run: 	cp ./build/stellarium-web-engine.js ./web-frontend/src/assets/js/ && cp ./build/stellarium-web-engine.wasm ./web-frontend/src/assets/js/

    - name: Build
      uses: docker://node:12.10.0-alpine
      with:
        args: /bin/sh -c "cd /github/workspace/web-frontend && yarn build"

    # Push the statics to github-pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web-frontend/dist
        cname: next.theduckening.earth
